---
name: Typecheck

on: [push, workflow_dispatch]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --verbose

      - name: Build common folder
        run: npx tsc --project common

      - name: Typecheck frontend folder
        run: npx tsc --project frontend --noEmit

      - name: Typecheck backend folder
        run: npx tsc --project backend --noEmit
